[window]
opacity = 0.8
padding.x = 8
padding.y = 3

[font]
size = 11
normal = {family = "monospace", style = "Regular"}
# normal = {family = "Nimbus Mono PS", style = "Regular"}
# normal = {family = "Liberation Mono", style = "Regular"}

[terminal]
shell = "zsh"

[colors]
[colors.primary]
foreground = "#dddddd"
# background = "#101a21"
background = "#000000"

[general]
# campbell
# ayu_dark
# github_dark
import = [
    "~/.config/alacritty/themes/themes/github_dark.toml"
]
