[window]
opacity = 0.9
padding.x = 8
padding.y = 3

[font]
size = 10
normal = {family = "monospace", style = "Regular"}
# normal = {family = "Nimbus Mono PS", style = "Regular"}
# normal = {family = "Liberation Mono", style = "Regular"}

