#!/usr/bin/env bash
echo "SUPER+1 Mudar para o workspace 1"
echo "SUPER+2 Mudar para o workspace 2"
echo "SUPER+3 Mudar para o workspace 3"
echo "SUPER+4 Mudar para o workspace 4"
echo "SUPER+5 Mudar para o workspace 5"
echo "SUPER+6 Mudar para o workspace 6"
echo "SUPER+7 Mudar para o workspace 7"
echo "SUPER+8 Mudar para o workspace 8"
echo "SUPER+9 Mudar para o workspace 9"
