echo "##################################### TABLE OF CONTENTS #####################################"
echo "* S W A Y"
echo " - SEARCH FOR 'SWAY' or 'SUPER'"
echo "* V I M"
echo "  - M o v e m e n t."
echo "  - I n s e r t  m o d e."
echo "  - E d i t."
echo "  - V i s u a l  m o d e."
echo "  - V i s u a l  c o m m a n d s."
echo "  - C u t  &  p a s t e."
echo "  - S e a r c h  &  r e p l a c e."
echo "  - S e a r c h  m u l t i - f i l e."
echo "  - E x i t."
echo "  - M u l t i  f i l e   (b u f f e r s)."
echo "  - T a b s."
echo "  - S e s s i o n s."
echo "  - C o m m a n d  L i n e."
echo "  - P l u g i n s."
echo "* S U B L I M E"
echo "* I 3 W M"
echo "  - B a s e."
echo "  - U t i l i t i e s."
echo "  - M u l t i m e d i a  c o n t r o l."
echo "* R A N G E R"
echo "  - B o o k m a r k s."
echo "  - t a b s."
echo "  - R a n g e r  m o v e m e n t."
echo "  - R a n g e r  f i l e s."
echo "  - R a n g e r  c o m m a n d s."
echo "  - F i l e  s u b s t i t u t i n g."
echo "  - C u s t o m."
echo "* T M U X"
echo "  - S e s s i o n s."
echo "  - W i n d o w s."
echo "  - P a n e s."
echo "  - S y n c."
echo "* T I L I X"
echo "  - A p p l i c a t i o n."
echo "  - t a b s (s e s s i o n s)."
echo "  - C o l u m n s."
echo "  - R e s i z e  c o l u m n."
echo "  - S e a r c h."
echo "* T E R M I N A T O R"
echo "  - C r e a t i o n  &  d e s t r u c t i o n."
echo "  - N a v e g a t  i o n."
echo "  - O r g a n i z a t i o n."
echo "  - M i s c e l a n e o u s."
echo "  - G r o u p i n g  &  B r o a d c a s t i n g."
echo "* F I R E F O X"
echo "  - C u r r e n t  p a g e."
echo "  - T a b s."
echo "  - H i s t o r y"
echo "  - B o o k m a r k s."
echo "  - T o o l s."
echo "  - P d f."
echo "  - M i s c."
echo "* V I M I U M C"
echo "  - V i m i u m c  n a v i g a t i o n."
echo "  - V o m n i b a r."
echo "  - F i n d."
echo "  - N a v i g a t i n g  h i s t o r y."
echo "  - T a b s."
echo "* T H U N D E R D B I R D"
echo "  - B a s e."
echo "  - E m a i l."
echo "  - C a l e n d a r."
echo "  - T a s k s."
echo "  - P l u g i n s."
echo "* L I B R E O F F I C E  W R I T E R"
echo "  - F u n c t i o n  k e y s."
echo "  - B a s e."
echo "  - P a r a g r a p h s."
echo "  - T a b l e s."
echo "  - M o v i n g  o b j e c t s."
echo "* L I B R E O F F I C E  C A L C"
echo "  - N a v i g a t i o n."
echo "  - F u n c t i o n  k e y s."
echo "  - F o r m a t  c e l l s."
echo "  - P i v o t  t a b l e."
echo "* F R A N Z"
echo "* H E X C H A T"
echo "* D I S C O R D"
echo "* R O F I"
echo "* G I M P [todo]"
echo "* I N K S C A P E [todo]"
echo "* S C R I B U S [todo]"
echo "* S Y N F Y G  [todo]"
echo "* L I G H T W O R K S [todo]"
echo "* N A T R O N [todo]"
echo "* B L E N D E R [todo]"
echo "* A L I A S E S [todo]"
echo ""
echo "###################################### VIM SHORTCUTS ########################################"
echo "--------------------------------------- VIM MOVEMENT ----------------------------------------"
echo "vim move: h           # left"
echo "vim move: j           # down"
echo "vim move: k           # up"
echo "vim move: l           # right"
echo "vim move: H           # to top of screen"
echo "vim move: M           # to middle of screen"
echo "vim move: L           # to bottom of screen"
echo "vim move: w           # jump forwards to the start of a word"
echo "vim move: W           # jump forwards to the start of a word (words can contain punctuation)"
echo "vim move: e           # jump forwards to the end of a word"
echo "vim move: E           # jump forwards to the end of a word (words can contain punctuation)"
echo "vim move: b           # jump backwards to the start of a word"
echo "vim move: B           # jump backwards to the start of a word (words can contain punctuation)"
echo "vim move: 0           # jump to the start of the line"
echo "vim move: ^           # jump to the first non-blank character of the line"
echo "vim move: $           # jump to the end of the line"
echo "vim move: g_          # jump to the last non-blank character of the line"
echo "vim move: gg          # go to the first line of the document"
echo "vim move: G           # go to the last line of the document"
echo "vim move: 5G          # go to line 5"
echo "vim move: fx          # jump to next occurrence of character x"
echo "vim move: tx          # jump to before next occurrence of character x"
echo "vim move: }           # jump to next paragraph (or function/block, when editing code)"
echo "vim move: {           # jump to previous paragraph (or function/block, when editing code)"
echo "vim move: zz          # center cursor on screen"
echo "vim move: Ctrl + b    # move back one full screen"
echo "vim move: Ctrl + f    # move forward one full screen"
echo "vim move: Ctrl + d    # move forward 1/2 a screen"
echo "vim move: Ctrl + u    # move back 1/2 a screen"
echo "vim move: lead + hjkl # move window"
echo "vim move: lead+cd     # cd current file's dir"
echo "-------------------------------------- VIM INSERT MODE --------------------------------------"
echo "vim insert: i         # insert before the cursor"
echo "vim insert: I         # insert at the beginning of the line"
echo "vim insert: a         # insert (append) after the cursor"
echo "vim insert: A         # insert (append) at the end of the line"
echo "vim insert: o         # append (open) a new line below the current line"
echo "vim insert: O         # append (open) a new line above the current line"
echo "vim insert: ea        # insert (append) at the end of the word"
echo "vim insert: Esc       # exit insert mode"
echo "---------------------------------------- VIM EDIT -------------------------------------------"
echo "vim edit: r           # replace a single character"
echo "vim edit: J           # join line below to the current one"
echo "vim edit: cc          # change (replace) entire line"
echo "vim edit: cw          # change (replace) to the start of the next word"
echo "vim edit: ce          # change (replace) to the end of the next word"
echo "vim edit: cb          # change (replace) to the start of the previous word"
echo "vim edit: c0          # change (replace) to the start of the line"
echo "vim edit: c$          # change (replace) to the end of the line"
echo "vim edit: s           # delete character and substitute text"
echo "vim edit: S           # delete line and substitute text (same as cc)"
echo "vim edit: xp          # transpose two letters (delete and paste)"
echo "vim edit: .           # repeat last command"
echo "vim edit: u           # undo"
echo "vim edit: Ctrl + r    # redo"
echo "------------------------------------- VIM VISUAL MODE ---------------------------------------"
echo "vim visual: v         # start visual mode, mark lines, then do a command (like y-yank)"
echo "vim visual: V         # start linewise visual mode"
echo "vim visual: o         # move to other end of marked area"
echo "vim visual: O         # move to other corner of block"
echo "vim visual: aw        # mark a word"
echo "vim visual: ab        # a block with ()"
echo "vim visual: aB        # a block with {}"
echo "vim visual: ib        # inner block with ()"
echo "vim visual: iB        # inner block with {}"
echo "vim visual: Esc       # exit visual mode"
echo "vim visual: Ctrl + v  # start visual block mode"
echo "vim visual: lead + *  # search current selection next"
echo "vim visual: lead + #  # search current selection prev"
echo "vim visual: lead + gv # quick search selection"
echo "vim visual: lead + r  # search and replace selection"
echo "vim visual: $1 $2 $3 $$ $q $e # surround sel. with (),[],[],"",'',"""
echo "---------------------------------- VIM VISUAL COMMANDS --------------------------------------"
echo "vim visual c: >       # shift text right"
echo "vim visual c: <       # shift text left"
echo "vim visual c: y       # yank (copy) marked text"
echo "vim visual c: d       # delete marked text"
echo "vim visual c: ~       # switch case"
echo "------------------------------------ VIM CUT & PASTE ----------------------------------------"
echo "vim cut paste: yy     # yank (copy) a line"
echo "vim cut paste: 2yy    # yank (copy) 2 lines"
echo "vim cut paste: yw     # yank (copy) the characters of the word from the cursor position to the start of the next word"
echo "vim cut paste: y$     # yank (copy) to end of line"
echo "vim cut paste: p      # put (paste) the clipboard after cursor"
echo "vim cut paste: P      # put (paste) before cursor"
echo "vim cut paste: dd     # delete (cut) a line"
echo "vim cut paste: 2dd    # delete (cut) 2 lines"
echo "vim cut paste: dw     # delete (cut) the characters of the word from the cursor position to the start of the next word"
echo "vim cut paste: D      # delete (cut) to the end of the line"
echo "vim cut paste: d$     # delete (cut) to the end of the line"
echo "vim cut paste: d^     # delete (cut) to the first non-blank character of the line"
echo "vim cut paste: d0     # delete (cut) to the begining of the line"
echo "vim cut paste: x      # delete (cut) character"
echo "vim cut paste: lead + pp  # toggle paste mode"
echo "--------------------------------- VIM SEARCH & REPLACE --------------------------------------"
echo "vim search replace: spacebar        # search"
echo "vim search replace: ctrl+spacebar   # search prev"
echo "vim search replace: lead+g          # quick search"
echo "vim search replace: /pattern        # search for pattern"
echo "vim search replace: ?pattern        # search backward for pattern"
echo "vim search replace: \vpattern       # 'very magic' pattern: non-alphanumeric characters are interpreted as special regex symbols (no escaping needed)"
echo "vim search replace: n               # repeat search in same direction"
echo "vim search replace: N               # repeat search in opposite direction"
echo "vim search replace: :%s/old/new/g   # replace all old with new throughout file"
echo "vim search replace: :%s/old/new/gc  # replace all old with new throughout file with confirmations"
echo "vim search replace: :noh            # remove highlighting of search matches"
echo "---------------------------------- VIM SEARCH MULTI FILE ------------------------------------"
echo "vim search multi: :vimgrep /pattern/ {file} # search for pattern in multiple files"
echo "vim search multi: :cn                       # jump to the next match"
echo "vim search multi: :cp                       # jump to the previous match"
echo "vim search multi: :copen                    # open a window containing the list of matches"
echo "--------------------------------------- VIM EXIT --------------------------------------------"
echo "vim exit: :w or :w /path                    # write (save) the file, but don't exit"
echo "vim exit: :W                                # write (save) the file as sudo, but don't exit"
echo "vim exit: :w !sudo tee %                    # write out the current file using sudo"
echo "vim exit: :wq or :x or ZZ                   # write (save) and quit"
echo "vim exit: :q                                # quit (fails if there are unsaved changes)"
echo "vim exit: :q! or ZQ                         # quit and throw away unsaved changes"
echo "vim exit: :bd or bd!                        # Close the file (buffer)"
echo "----------------------------------- VIM MULTIPLE FILES--------------------------------------"
echo "vim multi file: lead+q              # Open buffer for scripbble"
echo "vim multi file: lead+bd             # close current buffer"
echo "vim multi file: lead+ba             # close all buffers"
echo "vim multi file: :e file             # edit a file in a new buffer"
echo "vim multi file: :bnext or :bn       # go to the next buffer"
echo "vim multi file: :bprev or :bp       # go to the previous buffer"
echo "vim multi file: :bd                 # delete a buffer (close a file)"
echo "vim multi file: :ls                 # list all open buffers"
echo "vim multi file: :sp file            # open a file in a new buffer and split window"
echo "vim multi file: :vsp file           # open a file in a new buffer and vertically split window"
echo "vim multi file: Ctrl + wv           # split window vertically "
echo "vim multi file: Ctrl + ws           # split window horizontally"
echo "vim multi file: Ctrl + ww           # switch windows"
echo "vim multi file: Ctrl + wq           # quit a window"
echo "vim multi file: Ctrl + wv           # split window vertically"
echo "vim multi file: Ctrl + wh           # move cursor to the left window (vertical split)"
echo "vim multi file: Ctrl + wl           # move cursor to the right window (vertical split)"
echo "vim multi file: Ctrl + wj           # move cursor to the window below (horizontal split)"
echo "vim multi file: Ctrl + wk           # move cursor to the window above (horizontal split)"
echo "--------------------------------------- VIM TABS --------------------------------------------"
echo "vim tabs: lead+tn                   # open a file in a new tab"
echo "vim tabs: lead+to                   # tab only"
echo "vim tabs: lead+tc                   # tab close"
echo "vim tabs: lead+tm                   # tab move "
echo "vim tabs: lead+te                   # tab edit"
echo "vim tabs: <number>gt                # move to tab <number>"
echo "vim tabs: Ctrl + wT                 # move the current split window into its own tab"
echo "vim tabs: gt or :tabnext or :tabn   # move to the next tab"
echo "vim tabs: gT or :tabprev or :tabp   # move to the previous tab"
echo "vim tabs: :tabmove <number>         # move current tab to the <number>th position (indexed from 0)"
echo "vim tabs: :tabclose or :tabc        # close the current tab and all its windows"
echo "vim tabs: :tabonly or :tabo         # close all tabs except for the current one"
echo "vim tabs: :tabdo command            # run the command on all tabs (e.g. :tabdo q - closes all opened tabs)"
echo "--------------------------------------- VIM CODE FOLDING ------------------------------------"
echo "vim folding: zo / zO                # Open"
echo "vim folding: zc / zC                # Close"
echo "vim folding: za / zA                # Toggle"
echo "vim folding: zv                     # Open folds for this line"
echo "vim folding: zM                     # Close all"
echo "vim folding: zR                     # Open all"
echo "vim folding: zm                     # Fold more (foldlevel += 1)"
echo "vim folding: zr                     # Fold less (foldlevel -= 1)"
echo "vim folding: zx                     # Update folds"
echo "vim folding: ADVICE                 # I recommend using vim-anyfold for better folding."
echo "--------------------------------------- VIM SESSIONS -----------------------------------------"
echo "vim sessions: ":mksession /path"    # Save the curren vim session."
echo "vim sessions: ":source /path"       # Load the specified vim session."
echo "--------------------------------------- VIM COMMAND LINE -----------------------------------"
echo "vim command line: iab               # Insert timestamp"
echo "vim command line: $q                # Delete until the last slash"
echo "--------------------------------------- VIM PLUGINS -----------------------------------------"
echo "vim plugin nerdtree: lead+nn        # Toggle tree"
echo "vim plugin nerdtree: lead+nf        # Tree from bookmark"
echo "vim plugin nerdtree: lead+nb        # Open Bookmark"
echo "vim plugin buferexplorer: lead+o    # See and manage current buffers"
echo "vim plugin ctrlp.vim: lead+f        # Recent files"
echo "vim plugin ctrlp.vim: lead+b        # Recent buffers"
echo "vim plugin ctrlp.vim: <C-f>         # Recent files  on CWD"
echo "vim plugin zen mode: lead+z         # Toggle zen mode"
echo "vim plugin mult cursors: '<C-s>'    # multi_cursor_start_word_key"
echo "vim plugin mult cursors: '<A-s>'    # multi_cursor_select_all_word_key"
echo "vim plugin mult cursors: 'g<C-s>'   # multi_cursor_start_key"
echo "vim plugin mult cursors: 'g<A-s>'   # multi_cursor_select_all_key"
echo "vim plugin mult cursors: '<C-s>'    # multi_cursor_next_key"
echo "vim plugin mult cursors: '<C-p>'    # multi_cursor_prev_key"
echo "vim plugin mult cursors: '<C-x>'    # multi_cursor_skip_key"
echo "vim plugin mult cursors: '<Esc>'    # multi_cursor_quit_key"
echo "vim plugin yankstack: <C-p>         # yankstack_substitute_older_paste "
echo "vim plugin yankstack: <C-n>         # yankstack_substitute_newer_paste"
echo "vim plugin ctrl-p: '<C-f>'          # g:ctrlp_map"
echo "vim plugin ctrl-p: <lead>j          # :CtrlP<cr>"
echo "vim plugin ctrl-p: <C-b>            # :CtrlPBuffer<cr>"
echo "vim plugin snipmate: <C-j>          # autocomplete"
echo "vim plugin surround: Si             # Surrounds a string with _() gettext annotation"
echo "vim plugin ale: <lead>a             # Go to the next Ale syntax/lint error"
echo "vim plugin spell checking: lead+ss  # toggle spellcheck"
echo "vim plugin cope: cc                 # Open errors bot-right"
echo "vim plugin cope: lead+co            # Open errors in new tab"
echo "vim plugin cope: lead+n             # Next-error"
echo "vim plugin cope: lead+p             # Prev-error"
echo "vim plugin anyfold: [[              # Move to the beginning of the current block."
echo "vim plugin anyfold: ]]              # Move to the end of the current block."
echo "vim plugin anyfold: ]k              # Move to the end of the previous block."
echo "vim plugin anyfold: [j              # Move to the beginning of the next block."
echo "#################################### SUBLIME SHORTCUTS ######################################"
echo "sublime: ctrl + o                   # Open file"
echo "sublime: ctrl + shift + o           # Open directory"
echo "sublime: ctrl + shift + s           # Save as"
echo "sublime: ctrl + n                   # New tab"
echo "sublime: ctrl + w                   # Close tab"
echo "sublime: mayus + alt + number       # Set N of columns"
echo "sublime: ctrl + number              # Select column"
echo "sublime: ctrl + mayus + number      # Move tab to n column"
echo "sublime: ctrl + shift + p           # Change syntax"
echo "sublime: ctrl + k + b               # Toggle tree"
echo ""
echo "##################################### I3WM SHORTCUTS ########################################"
echo "---------------------------------------- I3WM BASE ------------------------------------------"
echo "i3wm base: ctrl + number           # Go to workspace"
echo "i3wm base: ctrl + next/prior       # Go to next/prior workspace"
echo "i3wm base: cmd + arrows            # Select application in the current workspace"
echo "i3wm base: cmd + shift + number    # Move application to workspace"
echo "i3wm base: cmd + shift + arrows    # Move application"
echo "i3wm base: cmd + r                 # Resize application"
echo "i3wm base: cmd + a                 # Focus parent"
echo "i3wm base: cmd + space             # Toggle float"
echo "i3wm base: cmd + shift + minus     # Send to Scratchpad"
echo "i3wm base: cmd + minus             # Toggle Scratchpad"
echo "i3wm base: cmd + ctrl+x            # XKill"
echo "i3wm base: cmd + n                 # Show window title"
echo "i3wm base: cmd + u                 # Hide window title"
echo "-------------------------------------- I3WM UTILITIES ---------------------------------------"
echo "i3wm util: cmd + F1                # Focus ranger"
echo "i3wm util: cmd + F2                # Pcmanfm"
echo "i3wm util: cmd + shift+F2          # Pcmanfm as sudo"
echo "i3wm util: cmd + F3                # calculator"
echo "i3wm util: cmd + F4                # i3-easyfocus"
echo "i3wm util: cmd + d                 # rofi"
echo "i3wm util: cmd + Tab               # rofi-windows"
echo "i3wm util: cmd + ctrl + s          # rofi-shortcuts"
echo "i3wm util: cmd + ctrl + d          # rofi-zeal"
echo "i3wm util: cmd + ctrl + f          # rofi-search"
echo "i3wm util: cmd + z                 # dboxmenu"
echo "i3wm util: cmd + ctrl + c          # zenity-calendar"
echo "i3wm util: cmd + ctrl + w          # gnome-weather"
echo "i3wm util: cmd + ctrl + a          # activities"
echo "i3wm util: cmd + ctrl + b          # bmenu"
echo "-------------------------------- I3WM MULTIMEDIA CONTROLS -----------------------------------"
echo "i3wm multi:                        # Mute"
echo "i3wm multi:                        # Vol up"
echo "i3wm multi::                       # Vol down"
echo "i3wm multi::                       # Play/pause"
echo "i3wm multi::                       # brightness up"
echo "i3wm multi::                       # brightness down"
echo "i3wm multi::                       # Toggle trackpad"
echo "------------------------------- I3WM NOTIFICATIONS (dunst) ----------------------------------"
echo "i3wm notif: ctrl+mod1+h            # Close all notifications"
echo "i3wm notif: ctrl+mod4+h            # Show n otifications h istory"
echo "i3wm notif: ctrl+mod1+p            # Show c ontext"
echo ""
echo "################################### RANGER SHORTCUTS ########################################"
echo "----------------------------------- RANGER BOOKMARKS ----------------------------------------"
echo "ranger bookmarks: m - letter      # Create bookmark"
echo "ranger bookmarks: um - letter     # Delete bookmark"
echo "ranger bookmarks: ' or `          # Go to a bookmark"
echo "ranger bookmarks: gh                      # Go to home"
echo "----------------------------------- RANGER TABS ---------------------------------------------"
echo "ranger tabs: C-n                  # Create new tab"
echo "ranger tabs: C-w                  # Close current tab"
echo "ranger tabs: tab                  # Next tab"
echo "ranger tabs: shift + tab          # Previous tab"
echo "ranger tabs: alt + [n]            # goto / create [n] tab"
echo "----------------------------------- RANGER MOVEMENT -----------------------------------------"
echo "ranger movement: k                # up"
echo "ranger movement: j                # down"
echo "ranger movement: h                # parent directory"
echo "ranger movement: l                # subdirectory"
echo "ranger movement: gg               # go to top of list"
echo "ranger movement: G                # go t bottom of list"
echo "ranger movement: J                # half page down"
echo "ranger movement: K                # half page up"
echo "ranger movement: H                # History Back"
echo "ranger movement: L                # History Forward"
echo "----------------------------------- RANGER FILES --------------------------------------------"
echo "ranger files: <Enter>             # Open"
echo "ranger files: r                   # open file with"
echo "ranger files: z                   # toggle settings"
echo "ranger files: o                   # change sort order"
echo "ranger files: zh                  # view hidden files"
echo "ranger files: cw                  # rename current file"
echo "ranger files: yy                  # yank / copy"
echo "ranger files: dd                  # cut"
echo "ranger files: pp                  # paste"
echo "ranger files: /                   # search for files :search"
echo "ranger files: n                   # next match"
echo "ranger files: N                   # prev match"
echo "ranger files: <del>               # Delete"
echo "ranger: 1l                        # Unzip selected file (uncompress)"
echo "----------------------------------- RANGER COMMANDS -----------------------------------------"
echo "ranger commands: :                # Execute Range Command"
echo "ranger commands: !                # Execute Shell Command"
echo "ranger commands: chmod            # Change file Permissions"
echo "ranger commands: du               # Disk Usage Current Directory"
echo "----------------------------------- FILE SUBSTITUTING ---------------------------------------"
echo "ranger subst: %f                  # Substitute highlighted file"
echo "ranger subst: %d                  # Substitute current directory"
echo "ranger subst: %s                  # Substitute currently selected files"
echo "ranger subst: %t                  # Substitute currently tagged files"
echo "ranger subst: :bulkrename %s      # Example for substitution"
echo "----------------------------------- RANGER CUSTOM -------------------------------------------"
echo "ranger: cmd + f1                  # Focus ranger"
echo ""
echo "##################################### TMMUX SHORTCUTS #######################################"
echo "-------------------------------------- TMUX SESSIONS ----------------------------------------"
echo "tmux sessions: mode -> s          # Select session. Kill one with 'x' "
echo "--------------------------------------- TMUX WINDOWS ----------------------------------------"
echo "tmux windows mode -> w            # Select window. Kill one with 'x'"
echo "-------------------------------------- TMUX PANES -------------------------------------------"
echo "tmux panes: mode -> alt + number  # Choose a different pane layout. Kill one with 'exit'"
echo "tmux panes: mode -> arrow         # Select a pane'"
echo "-------------------------------------- TMUX SYNC --------------------------------------------"
echo "tmux sync: mode -> x              # Toggle sync panes on/off"
echo "##################################### TILIX SHORTCUTS #######################################"
echo "------------------------------------ TILIX APPLICATION --------------------------------------"
echo "tilix appl: F11                   # Full screen"
echo "tilix appl: F12                   # Show sessions sidebar"
echo "tilix appl: unasigned             # Open settings"
echo "tilix appl: unasigned             # Open shortcuts cheatsheet"
echo "--------------------------------- TILIX TABS (SESSIONS) ------------------------------------"
echo "tilix tabs: mayus + ctrl + t      # New session"
echo "tilix tabs: mayus + ctrl + n      # New window"
echo "tilix tabs: ctrl + pg up          # Next session"
echo "tilix tabs: ctrl + pg down        # Previous session"
echo "tilix tabs: ctrl + alt + [n]      # Show session n"
echo "tilix tabs: ctrl + alt + [n]      # Close session"
echo "tilix tabs: mayus + ctrl + s      # Save session"
echo "tilix tabs: unasigned             # Save session on file"
echo "------------------------------------ TILIX COLUMNS ------------------------------------------"
echo "tilix columns: ctrl + alt + r     # Split right"
echo "tilix columns: ctrl + alt + d     # Split down"
echo "tilix columns: ctrl + alt + a     # Split on aureal pattern"
echo "tilix wind: alt + arrow           # Select column"
echo "--------------------------------- TILIX RESIZE COLUMN ---------------------------------------"
echo "tilix resize: ctrl + alt + up     # Resize up"
echo "tilix resize: ctrl + alt + down   # Resize down"
echo "tilix resize: ctrl + alt + left   # Resize left"
echo "tilix resize: ctrl + alt + right  # Resize right"
echo "----------------------------------  TILIX SEARCH --------------------------------------------"
echo "tilix resize: ctrl + shift + f    # Search"
echo "tilix resize: ctrl + shift + g    # Search next"
echo "tilix resize: ctrl + shift + h    # Search prev"
echo ""
echo "################################### TERMINATOR SHORTCUTS ####################################"
echo "------------------------------ TERMINATOR CREATION & DESTRUCTION ----------------------------"
echo "terminator creation: Ctrl+Shift+O # Split terminals Horizontally"
echo "terminator creation: Ctrl+Shift+E # Split terminals Vertically"
echo "terminator creation: Ctrl+Shift+T # Open new tab"
echo "terminator creation: Ctrl+Shift+I # Open a new window (as part of the same process)."
echo "terminator creation: Alt + L      # Open layout launcher"
echo "terminator creation: Ctrl + shift + W # Close current terminal."
echo "terminator creation: Ctrl+Shift+Q # Close current window."
echo "----------------------------------- TERMINATOR NAVEGATION -----------------------------------"
echo "terminator navegation: Alt+Up # Move to the terminal above the current one."
echo "terminator navegation: Alt+Down # Move to the terminal below the current one."
echo "terminator navegation: Alt+Left # Move to the terminal left of the current one."
echo "terminator navegation: Alt+Right # Move to the terminal right of the current one."
echo "terminator navegation: Ctrl+PageDown # Move to next Tab."
echo "terminator navegation: Ctrl+PageUp # Move to previous Tab."
echo "terminator navegation: Ctrl+Shift+N or Ctrl+Tab # Move to next terminal within the same tab, use Ctrl+PageDown to move to the next tab.  If cycle_term_tab is False, cycle within the same tab will be disabled."
echo "terminator navegation: Ctrl+Shift+P or Ctrl+Shift+Tab # Move  to previous terminal within the same tab, use Ctrl+PageUp to move to the previous tab.  If cycle_term_tab is False, cycle within the same tab will be disabled."
echo "----------------------------------- TERMINATOR ORGANIZATION ---------------------------------"
echo "terminator organ: Ctrl+Shift+Right    # Move parent dragbar Right."
echo "terminator organ: Ctrl+Shift+Left     # Move parent dragbar Left."
echo "terminator organ: Ctrl+Shift+Up       # Move parent dragbar Up."
echo "terminator organ: Ctrl+Shift+Down     # Move parent dragbar Down."
echo "terminator organ: Super+R             # Rotate terminals clockwise."
echo "terminator organ: Drag and Drop       # Or you could just drag & drop."
echo "terminator organ: Ctrl+Shift+PageDown # Swap tab position with next Tab."
echo "terminator organ: Ctrl+Shift+PageUp   # Swap tab position with previous Tab."
echo "----------------------------------- TERMINATORMISCELANEOUS ----------------------------------"
echo "terminator misc: Ctrl+Shift+C   # Copy selected text to clipboard."
echo "terminator misc: Ctrl+Shift+V   # Paste clipboard text."
echo "terminator misc: Ctrl+Shift+S   # Hide/Show Scrollbar."
echo "terminator misc: Ctrl+Shift+F   # Search within terminal scrollback."
echo "terminator misc: Ctrl+Shift+R   # Reset terminal state."
echo "terminator misc: Ctrl+Shift+G   # Reset terminal state and clear window."
echo "terminator misc: Ctrl+Plus (+)  # Increase font size. Note: This may require you to press shift, depending on your keyboard."
echo "terminator misc: Ctrl+Minus (-) # Decrease font size. Note: This may require you to press shift, depending on your keyboard."
echo "terminator misc: Ctrl+Zero (0)  # Restore font size to original setting."
echo "terminator misc: Ctrl+Alt+W     # Rename window title."
echo "terminator misc: Ctrl+Alt+A     # Rename tab title."
echo "terminator misc: Ctrl+Alt+X     # Rename terminal title."
echo "terminator misc: Super+1        # Insert terminal number, i.e. 1 to 12."
echo "terminator misc: Super+0        # Insert padded terminal number, i.e. 01 to 12"
echo "--------------------------------- TERMINATOR GROUPING & BROADCASTING ------------------------"
echo "terminator broad: F11               # Toggle window to fullscreen."
echo "terminator broad: Ctrl  +Shift + X  # Toggle between showing all terminals and only showing the current one (maximise)."
echo "terminator broad: Ctrl+Shift+Z      # Toggle between showing all terminals and only showing a scaled version of the current one (zoom)."
echo "terminator broad: Ctrl+Shift+Alt+A  # Hide the initial window. Note that this is a global binding, and can only be bound once."
echo "terminator broad: Super+T           # Group all terminals in the current tab so input sent to one of them, goes to all terminals in the current tab."
echo "terminator broad: Super+Shift+T     # Remove grouping from all terminals in the current tab."
echo "terminator broad: Super+G           # Group all terminals so that any input sent to one of them, goes to all of them."
echo "terminator broad: Super+Shift+G     # Remove grouping from all terminals."
echo "terminator broad: Alt+A             # Broadcast to All terminals."
echo "terminator broad: Alt+G             # Broadcast to Grouped terminals."
echo "terminator broad: Alt+O             # Broadcast Off."
echo ""
echo "################################### FIREFOX SHORTCUTS #######################################"
echo "--------------------------------- FIREFOX CURRENT PAGE ------------------------"
echo "firefox current pag: F6           # move to the next frame"
echo "firefox current pag: Shift + F6   # move to the prev frame"
echo "--------------------------------- FIREFOX EDITING ------------------------"
echo "firefox edit: Ctrl + Backspace      # Delete Word to the Left   "
echo "firefox edit: Ctrl + Del            # Delete Word to the Right  "
echo "firefox edit: Ctrl + ←              # Go one Word to the Left   "
echo "firefox edit: Ctrl + →              # Go one Word to the Right  "
echo "firefox edit: Ctrl + Home           # Go to Beginning of Text   "
echo "firefox edit: Ctrl + End            # Go to End of Text   "
echo "--------------------------------- FIREFOX SEARCH ------------------------"
echo "firefox search: Ctrl + F                       # Find"
echo "firefox search: F3 Ctrl + G                    # Find Again   "
echo "firefox search: Shift + F3 Ctrl + Shift + G    # Find Previous  "
echo "firefox search: '                              # Quick Find within link-text only"
echo "firefox search: /                              # Quick Find"
echo "firefox search: Esc                            # Close the Find or Quick Find bar - when the Find or Quick Find bar is focused  "
echo "firefox search: Alt + ↓↑                       # Switch Search Engine - after you have written something in the address bar   "
echo "firefox search: Ctrl + K Ctrl + J              # Focus Address bar for Web Search (writes "? " there)  - if search bar is not shown   "
echo "firefox search: Ctrl + K Ctrl + J              # Focus Search bar - if search bar is shown  "
echo "firefox search: Ctrl + ↓ Ctrl + ↑              # Change the Default Search Engine - in the Search bar or the Search field of the New Tab page.  "
echo "firefox search: Alt + ↓ Alt + ↑ F4             # View menu to switch, add or manage search engines - when the Search bar is focused "
echo "--------------------------------- FIREFOX TABS ------------------------"
echo "firefox tabs: Ctrl + W Ctrl + F4              # Close Tab - except for Pinned Tabs"
echo "firefox tabs: Ctrl + Shift + W Alt + F4       # Close Window  "
echo "firefox tabs: Ctrl + Tab                      # Cycle through Tabs in Recently Used Order -if enabled in Preferences "
echo "firefox tabs: Ctrl + Q                        # Quit"
echo "firefox tabs: Ctrl+Page Up, Ctrl+Shift+Tab    # Go one Tab to the Left"
echo "firefox tabs: Ctrl + Page Down Ctrl + Tab     # Go one Tab to the Right * if the setting Ctrl+Tab cycles through tabs in recently used order is disabled in Preferences"
echo "firefox tabs: Alt + 1                         # to 8 Go to Tab 1 to 8"
echo "firefox tabs: Alt + 9                         # Go to Last Tab"
echo "firefox tabs: Ctrl + Shift + Page Up          # Move Tab Left"
echo "firefox tabs: Ctrl + Shift + Page Down        # Move Tab Right"
echo "firefox tabs: Ctrl + Shift + Home             # Move Tab to start - requires the currently selected tab to be "in focus" for instance, by hitting Alt + D to focus the address bar, and then Shift + Tab until you reach the browser tab bar."
echo "firefox tabs: Ctrl + Shift + End              # Move Tab to end - requires the currently selected tab to be "in focus" for instance, by hitting Alt + D to focus the address bar, and then Shift + Tab until you reach the browser tab bar."
echo "firefox tabs: Ctrl + M                        # Mute/Unmute Audio"
echo "firefox tabs: Ctrl + T                        # New Tab"
echo "firefox tabs: Ctrl + N                        # New Window"
echo "firefox tabs: Ctrl + Shift + P                # New Private Window"
echo "firefox tabs: Alt + Shift + Enter             # Open Address or Search in New Background Tab - from address bar"
echo "firefox tabs: Alt + Enter                     # Open Address or Search in New Foreground Tab - from address bar or Search bar"
echo "firefox tabs: Shift + Enter                   # Open Address or Search in New Window - from address bar or the Search field on the New Tab page"
echo "firefox tabs: Ctrl + Enter                    # Open Search in New Background Tab - from the Search field on the New Tab page. (see note, below)"
echo "firefox tabs: Ctrl + Shift + Enter            # Open Search in New Foreground Tab - from the Search field on the New Tab page. Note: The Foreground and Background Tab shortcuts are switched if the setting When you open a link in a new tab, switch to it immediately is enabled in Preferences"
echo "firefox tabs: Enter                           # Open Focused Bookmark or Link in Current Tab"
echo "firefox tabs: Ctrl + Enter                    # Open Focused Bookmark in New Foreground Tab"
echo "firefox tabs: Ctrl + Shift + Enter            # Open Focused Bookmark in New Background Tab"
echo "firefox tabs: Ctrl + Enter                    # Open Focused Link in New Background Tab (see note, below)"
echo "firefox tabs: Ctrl + Shift + Enter            # Open Focused Link in New Foreground Tab Note: The Foreground and Background Tab shortcuts are switched if the setting When you open a link in a new tab, switch to it immediately is enabled in Preferences"
echo "firefox tabs: Shift + Enter                   # Open Focused Bookmark or Link in New Window"
echo "firefox tabs: Ctrl + Shift + T                # Undo Close Tab"
echo "firefox tabs: Ctrl + Shift + N                # Undo Close Window"
echo "firefox tabs: Ctrl + Shift + X                # Moves the URL left or right (if cursor is in the address bar)"
echo "--------------------------------- FIREFOX HISTORY ------------------------"
echo "firefox history: Ctrl + H                     # History sidebar"
echo "firefox history: Ctrl + Shift + H             # Library window (History)  "
echo "firefox history:  Ctrl + Shift + Del          # Clear Recent History"
echo "--------------------------------- FIREFOX BOOKMARKS ------------------------"
echo "firefox marks: Ctrl + D                       # Bookmark This Page"
echo "firefox marks: Ctrl + B                       # Bookmarks sidebar"
echo "firefox marks: Ctrl + Shift + O               # Library window (Bookmarks)  "
echo "--------------------------------- FIREFOX TOOLS ------------------------"
echo "firefox tools: Ctrl + Shift + Y               # Downloads"
echo "firefox tools: Ctrl + Shift + A               # Add-ons"
echo "firefox tools: F12, Ctrl + Shift + I          # Toggle Developer Tools"
echo "firefox tools: Ctrl + Shift + K               # Web Console"
echo "firefox tools: Ctrl + Shift + C               # Inspector"
echo "firefox tools: Ctrl + Shift + S               # Debugger"
echo "firefox tools: Shift + F7                     # Style Editor"
echo "firefox tools: Shift + F5                     # Profiler"
echo "firefox tools: Ctrl + Shift + E               # Network"
echo "firefox tools: Shift + F2                     # Developer Toolbar"
echo "firefox tools: Ctrl + Shift + M               # Responsive Design View"
echo "firefox tools: Shift + F4                     # Scratchpad"
echo "firefox tools: Ctrl + U                       # Page Source"
echo "firefox tools: Ctrl + Shift + J               # Browser Console"
echo "firefox tools: Ctrl + I                       # Page Info "
echo "--------------------------------- FIREFOX PDF VIEWER ------------------------"
echo "firefox pdf: N or J or →                      # Next page"
echo "firefox pdf: P or K or ←                      # Previous page"
echo "firefox pdf: Ctrl +                           # Zoom in"
echo "firefox pdf: Ctrl -                           # Zoom out"
echo "firefox pdf: Ctrl + 0                         # Automatic Zoom"
echo "firefox pdf: R                                # Rotate the document clockwise"
echo "firefox pdf: Shift + R                        # Rotate counterclockwise "
echo "firefox pdf: Ctrl + Alt + P                   # Switch to Presentation Mode"
echo "firefox pdf: S                                # Choose Text Selection Tool"
echo "firefox pdf: H                                # Choose Hand Tool"
echo "firefox pdf: Ctrl + Alt + G                   # Focus the Page Number input box"
echo "--------------------------------- FIREFOX MISCELANEOUS ------------------------"
echo "firefox misc: Ctrl + Enter                    # Complete .com Address   "
echo "firefox misc: Shift + Del                     # Delete Selected Autocomplete Entry"
echo "firefox misc: F11                             # Toggle Full Screen  "
echo "firefox misc: Alt or F10                      # Toggle Menu Bar activation (showing it temporarily when hidden)"
echo "firefox misc: Ctrl + Alt + R                  # Toggle Reader Mode"
echo "firefox misc: F7                              # Caret Browsing"
echo "firefox misc: F6, Alt + D, Ctrl + L           # Focus Address Bar"
echo "firefox misc: F6, Ctrl + F                    # Focus Search Field in Library   "
echo "firefox misc: Esc                             # Stop Autoscroll Mode"
echo "firefox misc: Shift + F10                     # Toggle Context Menu"
echo "--------------------------------- FIREFOX SIMPLE TABS GROUPS ------------------------"
echo "firefox misc: Ctrl + space                    # Show groups"
echo "firefox misc: ctrl+1-9                        # Change to a group"
echo ""
echo "################################### VIMIUMC SHORTCUTS #######################################"
echo "---------------------------------- VIMIUMC  NAVIGATION --------------------------------------"
echo "vimiumc nav: ?                    # This help"
echo "vimiumc nav: <c-e>, j             # Scroll down"
echo "vimiumc nav: <c-y>, k             # Scroll up"
echo "vimiumc nav: h                    # Scroll left"
echo "vimiumc nav: l                    # Scroll right"
echo "vimiumc nav: gg                   # Scroll to the top of the page"
echo "vimiumc nav: G                    # Scroll to the bottom of the page"
echo "vimiumc nav: zH                   # Scroll all the way to the left"
echo "vimiumc nav: zL                   # Scroll all the way to the right"
echo "vimiumc nav: d                    # Scroll a page down"
echo "vimiumc nav: u                    # Scroll a page up"
echo "vimiumc nav: r                    # Reload current frame (use hard)"
echo "vimiumc nav: <a-r>                # Reload N tab(s) (use hard, bypassCache)"
echo "vimiumc nav: R                    # Reload N-th tab (use hard)"
echo "vimiumc nav: gs                   # View page source"
echo "vimiumc nav: yy                   # Copy page's info (use type=url/title/frame, decoded)"
echo "vimiumc nav: <f2>, <s-f1>         # Blur activeElement or refocus it (use flash, select=""/all/all-line/start/end)"
echo "vimiumc nav: <f1>                 # Simulate backspace once if focused"
echo "vimiumc nav: yf                   # Copy a link URL to the clipboard"
echo "vimiumc nav: p                    # Open the clipboard's URL in the current tab"
echo "vimiumc nav: P                    # Open the clipboard's URL in N new tab(s)"
echo "vimiumc nav: gu                   # Go up the URL hierarchy (use trailingSlash=null/true/false)"
echo "vimiumc nav: gU                   # Go to root of current URL hierarchy"
echo "vimiumc nav: gi                   # Focus the N-th visible text box on the page and cycle using tab (use keep, select=""/all/all-line/start/end)"
echo "vimiumc nav: f                    # Open a link in the current tab (use button=""/right, touch=false/true/"auto")"
echo "vimiumc nav: F                    # Open a link in a new tab"
echo "vimiumc nav: <a-f>                # Open multiple links in a new tab"
echo "vimiumc nav: [[                   # Follow the link labeled previous or "<""
echo "vimiumc nav: ]]                   # Follow the link labeled next or ">""
echo "vimiumc nav: gf                   # Cycle forward to the next frame on the page"
echo "vimiumc nav: gF                   # Select the tab's main/top frame"
echo "vimiumc nav: i                    # Enter insert mode (use key:string)"
echo "vimiumc nav: <f8>, v              # Enter visual mode"
echo "vimiumc nav: V                    # Enter visual line mode"
echo "vimiumc nav: m                    # Create a new mark (use swap)"
echo "vimiumc nav: `                    # Go to a mark (use prefix=true, swap, mapKey)"
echo "----------------------------------- VIMIUMC VOMNIBAR ----------------------------------------"
echo "vimiumc vomni: O                  # Open URL, history, ... in a new tab (use keyword, url)"
echo "vimiumc vomni: b                  # Open a bookmark"
echo "vimiumc vomni:B                   # Open a bookmark in a new tab"
echo "vimiumc vomni:T                   # Search through your open t a b s?"
echo "vimiumc vomni:ge                  # Edit the current URL"
echo "vimiumc vomni:gE                  # Edit the current URL and open in a new tab"
echo "vimiumc vomni:gn                  # Toggle styles of vomnibar page (use style=dark, current)"
echo "------------------------------------- VIMIUMC FIND ------------------------------------------ "
echo "vimiumc find: /                   # Enter find mode (use last, selected=true)"
echo "vimiumc find: n                   # Cycle forward to the next find match"
echo "vimiumc find: N                   # Cycle backward to the previous find match"
echo "vimiumc find: <a-n>               # Find the second or even earlier query words "
echo "-------------------------------- VIMIUMC NAVIGATING HISTORY ---------------------------------"
echo "vimiumc history: H                # Go back in history (use reuse=-2/-1)"
echo "vimiumc history: L                # Go forward in history (use reuse=-2/-1)"
echo "vimiumc history: <a-R>            # Reopen current page "
echo "------------------------------------- VIMIUMC TABS -------------------------------------"
echo "vimiumc tabs: gt, K, <a-v>, <a-s-c> # Go one tab right"
echo "vimiumc tabs: gT, J, <a-c>        # Go one tab left"
echo "vimiumc tabs: g0                  # Go to the first N-th tab"
echo "vimiumc tabs: g$                  # Go to the last N-th tab"
echo "vimiumc tabs: t, <a-t>            # Create new tab(s)"
echo "vimiumc tabs: yt                  # Duplicate current tab for N times"
echo "vimiumc tabs: x                   # Close N tab(s) (use mayClose, goto=""/left/right/previous)"
echo "vimiumc tabs: X                   # Restore closed tab(s)"
echo "vimiumc tabs: W                   # Move tab to next window (use right)"
echo "vimiumc tabs: <a-p>               # Pin or unpin N tab(s)"
echo "vimiumc tabs: <a-m>               # Mute or unmute current tab (use all, other)"
echo "vimiumc tabs: ^                   # Go to previously-visited tab on current window"
echo "vimiumc tabs: <<                  # Move tab to the left"
echo "vimiumc tabs: >>                  # Move tab to the right "
echo ""
echo "#################################### FRANZ SHORTCUTS ########################################"
echo "franz: ctrl-1-9                   # Select service"
echo "franz: Tab                        # Move inside of the service"
echo ""
echo "################################### HEXCHAT SHORTCUTS #######################################"
echo "hexchat: ctrl+Page                # Next or prev channel of the list"
echo "hexchat: alt-1-9                  # Go to channel"
echo "hexchat: Shift-Ctrl-page          # Change the order of the servers in the list"
echo "hexchat: alt+left or right        # Change tab, if they are enabled"
echo "hexchat: Shift-page               # Next or prev nickname on the list"
echo "hexchat: Tab                      # Complete the command"
echo "hexchat: Ctrl+S                   # Open server memu"
echo ""
echo "################################### DISCORD SHORTCUTS #######################################"
echo "discord: Ctrl + ALT + /         # Navigate Between Servers"
echo "discord: ALT + /                # Navigate Between Channels"
echo "discord: ALT + Shift + /        # Navigate Between Unread Channels"
echo "discord: Ctrl + Shift + ALT + / # Navigate Between Unread Channels with Mentions"
echo "discord: Escape                   # Mark Channel as Read  "
echo "discord: Shift + Escape           # Mark Server Read"
echo "discord: Ctrl + Slash             # Toggle Hotkeys   "
echo "discord: Ctrl + B                 # Return to Previous Text Channel"
echo "discord: Ctrl + ALT + A           # Return to Active Audio Channel   "
echo "discord: Ctrl + P                 # Toggle Pins Popout   "
echo "discord: Ctrl + I                 # Toggle Mentions Popout   "
echo "discord: Ctrl + U                 # Toggle Channel Member List"
echo "discord: Ctrl + E                 # Toggle Emoji Picker"
echo "discord: Shift + Page Up          # Jump to Oldest Unread Message  "
echo "discord: Ctrl + Shift + N         # Create or Join a Server"
echo "discord: Ctrl + Enter             # Answer Incoming Call   "
echo "discord: Ctrl + K                 # Find or Start a Direct Message"
echo "discord: Escape                   # Decline Incoming Call"
echo "discord: Ctrl + Shift + T         # Create A Private Group"
echo "discord: Ctrl + [                 # Start Call in Private Message or Group   "
echo "discord: Tab                      # Focus Text Area"
echo "discord: ALT + ←                  # Return to Connected Audio Channel"
echo "discord: ALT + →                  # Return to Previous Text Channel"
echo "discord: Ctrl + Shift + M         # Toggle Mute"
echo "discord: Ctrl + Shift + D         # Toggle Deafen"
echo "discord: Ctrl + Shift + H         # Get Help"
echo "discord: Ctrl + Shift + U         # Upload a File"
echo ""
echo "#################################### ROFI SHORTCUTS #########################################"
echo "rofi: Ctrl-v                      # Insert: Paste from clipboard"
echo "rofi: Ctrl-Shift-v, Shift-Insert: # Paste primary selection"
echo "rofi: Ctrl-u                      # Clear the line"
echo "rofi: Ctrl-                       # Beginning of line"
echo "rofi: Ctrl-e                      # End of line"
echo "rofi: Ctrl-f Right                # Forward one character"
echo "rofi: Alt-f, Ctrl-Right           # Forward one word"
echo "rofi: Ctrl-b, Left                # Back one character"
echo "rofi: Alt-b, Ctrl-Left            # Back one word"
echo "rofi: Ctrl-d, Delete              # Delete character"
echo "rofi: Ctrl-Alt-d                  # Delete word"
echo "rofi: Ctrl-h, Backspace, Shift-Backspace # Backspace (delete previous character)"
echo "rofi: Ctrl-Alt-h                  # Delete previous word"
echo "rofi: Ctrl-j,Ctrl-m,Enter         # Accept entry"
echo "rofi: Ctrl-n,Down                 # Select next entry"
echo "rofi: Ctrl-p,Up                   # Select previous entry"
echo "rofi: Page Up                     # Go to previous page"
echo "rofi: Page Down                   # Go to next page"
echo "rofi: Ctrl-Page Up                # Go to previous column"
echo "rofi: Ctrl-Page Down              # Go to next column"
echo "rofi: Ctrl-Enter                  # Use entered text as a command (in ssh/run modi)"
echo "rofi: Shift-Enter                 # Launch the application in a terminal (in run mode)"
echo "rofi: Shift-Enter                 # Return the selected entry and move to the next item while keeping rofi open. (in dmenu)"
echo "rofi: Shift-Right                 # Switch to the next mode. The list can be customized with the -switchers argument."
echo "rofi: Shift-Left                  # Switch to the previous mode. The list can be customized with the -switchers argument."
echo "rofi: Ctrl-Tab                    # Switch to the next mode. The list can be customized with the -switchers argument."
echo "rofi: Ctrl-Shift-Tab              # Switch to the previous mode. The list can be customized with the -switchers argument."
echo "rofi: Ctrl-space                  # Set selected item as input text."
echo "rofi: Shift-Del                   # Delete entry from history."
echo "rofi: grave                       # Toggle case sensitivity."
echo "rofi: Alt-grave                   # Toggle sorting."
echo "rofi: Alt-Shift-S                 # Take a screenshot and store it in the Pictures directory."
echo ""
echo "################################# THUNDERBIRD SHORTCUTS #####################################"
echo "------------------------------------- THUNDERBIRD BASE -------------------------------------"
echo "thunderbird base: F10, ctrl+f     # Open menu"
echo "thunderbird base: ctrl+w          # Close tab"
echo "thunderbird base: ctrl+pag        # Next/prev tab"
echo "thunderbird base: ctrl+pag        # Next/prev tab"
echo "thunderbird base: F11             # Open sidebar"
echo "------------------------------------- THUNDERBIRD EMAIL -------------------------------------"
echo "thunderbird email: ctrl+n         # New email"
echo "thunderbird email: ctrl+r         # Reply email"
echo "---------------------------------- THUNDERBIRD CALENDAR -------------------------------------"
echo "thunderbird cal: ctrl+shift+c     # Open calendar"
echo "thunderbird cal: ctrl+i           # New event"
echo "thunderbird cal: ctrl+a           # Select all events"
echo "thunderbird cal: ctrl+1-4         # Select day-week-multi-month"
echo "---------------------------------- THUNDERBIRD TASKS -------------------------------------"
echo "thunderbird task: ctrl+shift+c    # Open Tasks"
echo "thunderbird task: ctrl+d          # Create new task"
echo "---------------------------------- THUNDERBIRD PLUGINS -------------------------------------"
echo "thunderbird plug: alt+shift+ta    # Open Plugins settings"
echo "thunderbird plug: alt+shift+tt    # Open thunderstats"
echo ""
echo "############################## LIBREOFFICE WRITER SHORTCUTS #################################"
echo "------------------------------- LIBREOFFICE FUNCTION KEYS -----------------------------------"
echo "libre writer func: F2             # Formula Bar"
echo "libre writer func: Ctrl+F2        # Insert Fields"
echo "libre writer func: F3             # Complete AutoText"
echo "libre writer func: Ctrl+F3        # Edit AutoText"
echo "libre writer func: F4             # Open Data Source View"
echo "libre writer func: Shift+F4       # Select next frame"
echo "libre writer func: F5             # Navigator on/off"
echo "libre writer func: Ctrl+Shift+F5  # Navigator on, go to page number"
echo "libre writer func: F7             # Spellcheck"
echo "libre writer func: Ctrl+F7        # Thesaurus"
echo "libre writer func: F8             # Extension mode"
echo "libre writer func: Ctrl+F8        # Field shadings on / off"
echo "libre writer func: Shift+F8       # Additional selection mode"
echo "libre writer func: Ctrl+Shift+F8  # Block selection mode"
echo "libre writer func: F9             # Update fields"
echo "libre writer func: Ctrl+F9        # Show fields"
echo "libre writer func: Shift+F9       # C a l c ulate Table"
echo "libre writer func :Ctrl+Shift+F9  # Update Input Fields and Input Lists"
echo "libre writer func :Ctrl+F10       # Nonprinting Characters on/off"
echo "libre writer func: F11            # Styles and Formatting window on/off"
echo "libre writer func: Shift+F11      # Create Style"
echo "libre writer func: Ctrl+F11       # Sets focus to Apply Style box"
echo "libre writer func: Ctrl+Shift+F11 # Update Style"
echo "libre writer func: F12            # Numbering on"
echo "libre writer func: Ctrl+F12       # Insert or edit Table"
echo "libre writer func: Shift+F12      # Bullets on"
echo "libre writer func: Ctrl+Shift+F12 # Numbering / Bullets off"
echo "------------------------------- LIBREOFFICE WRITER BASE -----------------------------------"
echo "libre writer base: Ctrl+A              # Select All"
echo "libre writer base: Ctrl+J              # Justify"
echo "libre writer base: Ctrl+D              # Double Underline"
echo "libre writer base: Ctrl+E              # Centered"
echo "libre writer base: Ctrl+H              # Find and Replace"
echo "libre writer base: Ctrl+Shift+P        # Superscript"
echo "libre writer base: Ctrl+L              # Align Left"
echo "libre writer base: Ctrl+R              # Align Right"
echo "libre writer base: Ctrl+Shift+B        # Subscript"
echo "libre writer base: Ctrl+Y              # Redo last action"
echo "libre writer base: Ctrl+0 (zero)       # Apply Text Body paragraph style"
echo "libre writer base: Ctrl+1              # Apply Heading 1 paragraph style"
echo "libre writer base: Ctrl+2              # Apply Heading 2 paragraph style"
echo "libre writer base: Ctrl+3              # Apply Heading 3 paragraph style"
echo "libre writer base: Ctrl+4              # Apply Heading 4 paragraph style"
echo "libre writer base: Ctrl+5              # Apply Heading 5 paragraph style"
echo "libre writer base: Ctrl + Plus Key(+)  # C a l c ulates the s e l ected text and copies the result to the clipboard."
echo "libre writer base: Ctrl+Hyphen(-)      # Soft hyphens; hyphenation set by you."
echo "libre writer base: Ctrl+Shift+minus sign (-)  # Non-breaking hyphen (is not used for hyphenation)"
echo "libre writer base: Ctrl+multiplication sign * (only on number pad)  # Run macro field"
echo "libre writer base: Ctrl+Shift+Space   # Non-breaking spaces. Non-breaking spaces are not used for hyphenation and are not expanded if the text is justified."
echo "libre writer base: Shift+Enter        # Line break without paragraph change"
echo "libre writer base: Ctrl+Enter         # Manual page break"
echo "libre writer base: Ctrl+Shift+Enter   # Column break in multicolumnar texts"
echo "libre writer base: Alt+Enter          # Inserting a new paragraph without numbering inside a list. Does not work when the cursor is at the end of the list."
echo "libre writer base: Alt+Enter          # Inserting a new paragraph directly before or after a section, or before a table."
echo "libre writer base: Arrow Left         # Move cursor to left"
echo "libre writer base: Shift+Arrow Left   # Move cursor with selection to the left"
echo "libre writer base: Ctrl+Arrow Left    # Go to beginning of word"
echo "libre writer base: Ctrl+Shift+Arrow   # Selecting word by word"
echo "libre writer base: Arrow Right        # Move cursor to right"
echo "libre writer base: Shift+Arrow        # Move cursor with selection to the right"
echo "libre writer base: Ctrl+Arrow         # Go to start of next word"
echo "libre writer base: Ctrl+Shift+Arrow   # Selecting to the right word by word"
echo "libre writer base: Arrow Up           # Move cursor up one line"
echo "libre writer base: Shift+Arrow Up     # Selecting lines in an upwards direction"
echo "libre writer base: Ctrl+Arrow Up      # Move cursor to beginning of the previous paragraph"
echo "libre writer base: Ctrl+Shift+Arrow   # Select to beginning of paragraph. Next keystroke extends selection to beginning of previous paragraph"
echo "libre writer base: Arrow Down         # Move cursor down one line"
echo "libre writer base: Shift+Arrow Down   # Selecting lines in a downward direction"
echo "libre writer base: Ctrl+Arrow Down    # Move cursor to beginning of next paragraph."
echo "libre writer base: Ctrl+Shift+Arrow   # Select to end of paragraph. Next keystroke extends selection to end of next paragraph"
echo "libre writer base: Home               # Go to beginning of line"
echo "libre writer base: Home+Shift         # Go and select to the beginning of a line"
echo "libre writer base: End                # Go to end of line"
echo "libre writer base: End+Shift          # Go and select to end of line"
echo "libre writer base: Ctrl+Home          # Go to start of document"
echo "libre writer base: Ctrl+Home+Shift    # Go and select text to start of document"
echo "libre writer base: Ctrl+End           # Go to end of document"
echo "libre writer base: Ctrl+End+Shift     # Go and select text to end of document"
echo "libre writer base: Ctrl+PageUp        # Switch cursor between text and header"
echo "libre writer base: Ctrl+PageDown      # Switch cursor between text and footer"
echo "libre writer base: Insert             # Insert mode on/off"
echo "libre writer base: PageUp             # Screen page up"
echo "libre writer base: Shift+PageUp       # Move up screen page with selection"
echo "libre writer base: PageDown           # Move down screen page"
echo "libre writer base: Shift+PageDown     # Move down screen page with selection"
echo "libre writer base: Ctrl+Del           # Delete text to end of word"
echo "libre writer base: Ctrl+Backspace     # Delete text to beginning of word. In a list: delete an empty paragraph in front of the current paragraph"
echo "libre writer base: Ctrl+Del+Shift     # Delete text to end of sentence"
echo "libre writer base: Ctrl+Shift+Back.s  # Delete text to beginning of sentence"
echo "libre writer base: Ctrl+Tab           # Next suggestion with Automatic Word Completion"
echo "libre writer base: Ctrl+Shift+Tab     # Use previous suggestion with Automatic Word Completion"
echo "libre writer base: Ctrl+Alt+Shift+V   # Paste the contents of the clipboard as unformatted text."
echo "libre writer base: Ctrl + double-click or Ctrl + Shift + F10  # Use this combination to quickly dock or undock the Navigator, Styles and Formatting window, or other windows"
echo "-------------------- LIBREOFFICE WRITER PARAGRAPH AND HEADING LEVELS ------------------------"
echo "libre writer parag: Ctrl+Alt+UpArrow      # Move the active paragraph or selected paragraphs up one paragraph."
echo "libre writer parag: Ctrl+Alt+Down Arrow   # Move the active paragraph or selected paragraphs down one paragraph."
echo "libre writer parag: Tab                   # The heading in format "Heading X" (X = 1-9) is moved down one level in the outline."
echo "libre writer parag: Shift+Tab             # The heading in format "Heading X" (X = 2-10) is moved up one level in the outline."
echo "libre writer parag: CTRL+Tab              # Inserts tab in front of the heading."
echo "------------------------------- LIBREOFFICE WRITER TABLES -----------------------------------"
echo "libre writer tables: Ctrl+A                     # If the active cell is empty: selects the whole table. Otherwise: selects the contents of the active cell. Pressing again selects the entire table."
echo "libre writer tables: Ctrl+Home                  # If the active cell is empty: goes to the beginning of the table. Otherwise: first press goes to beginning of the active cell, second press goes to beginning of the current table, third press goes to beginning of document."
echo "libre writer tables: Ctrl+End                   # If the active cell is empty: goes to the end of the table. Otherwise: first press goes to the end of the active cell, second press goes to the end of the current table, third press goes to the end of the document."
echo "libre writer tables: Ctrl+Tab                   # Inserts a tab stop (only in tables). Depending on the Window Manager in use, Alt+Tab may be used instead."
echo "libre writer tables: Alt+Arrow Keys             # Increases/decreases the size of the column/row on the right/bottom cell edge"
echo "libre writer tables: Alt+Shift+Arrow Keys       # Increase/decrease the size of the column/row on the left/top cell edge"
echo "libre writer tables: Alt+Ctrl+Arrow Keys        # Like Alt, but only the active cell is modified"
echo "libre writer tables: Ctrl+Alt+Shift+Arrow Keys  # Like Alt, but only the active cell is modified"
echo "libre writer tables: Alt+Insert                 # 3 seconds in Insert mode, Arrow Key inserts row/column, Ctrl+Arrow Key inserts cell"
echo "libre writer tables: Alt+Del                    # 3 seconds in Delete mode, Arrow key deletes row/column, Ctrl+Arrow key merges cell with neighboring cell"
echo "libre writer tables: Shift+Ctrl+Del             # If no whole cell is selected, the text from the cursor to the end of the current sentence is deleted. If the cursor is at the end of a cell, and no whole cell is selected, the contents of the next cell are deleted. If no whole cell is selected and the cursor is at the end of the table, the paragraph following the table will be deleted, unless it is the last paragraph in the document. If one or more cells are selected, the whole rows containing the selection will be deleted. If all rows are selected completely or partially, the entire table will be deleted."
echo "-------------------------- LIBREOFFICE WRITER  MOVING OBJECTS -------------------------------"
echo "libre writer move obj: Esc                  # Cursor is inside a text frame and no text is selected: Escape selects the text frame. Text frame is selected: Escape clears the cursor from the text frame."
echo "F2 or Enter or any key                      # If a text frame is selected: positions the cursor to the end of the text in the text frame. If you press any key that produces a character on screen, and the document is in edit mode, the character is appended to the text."
echo "libre writer move obj: Alt+Arrow Keys       # Move object."
echo "libre writer move obj: Alt+Ctrl+Arrow Keys  # Resizes by moving lower right corner."
echo "libre writer move obj: Alt+Ctrl+Shift+Arrow # Keys  Resizes by moving top left corner."
echo "libre writer move obj: Ctrl+Tab             # Selects the anchor of an object (in Edit Points mode)."
echo ""
echo "############################### LIBREOFFICE CALC SHORTCUTS ##################################"
echo "------------------------------ LIBREOFFICE CALC NAVIGATION ----------------------------------"
echo "libre calc nav: Ctrl+Home         # Moves the cursor to the first cell in the sheet (A1)."
echo "libre calc nav: Ctrl+End          # Moves the cursor to the last cell on the sheet that contains data."
echo "libre calc nav: Home              # Moves the cursor to the first cell of the current row."
echo "libre calc nav: End               # Moves the cursor to the last cell of the current row."
echo "libre calc nav: Shift+Home        # Selects cells from the current cell to the first cell of the current row."
echo "libre calc nav: Shift+End         # Selects cells from the current cell to the last cell of the current row."
echo "libre calc nav: Shift+Page Up     # Selects cells from the current cell up to one page in the current column or extends the existing selection one page up."
echo "libre calc nav: Shift+Page Down   # Selects cells from the current cell down to one page in the current column or extends the existing selection one page down."
echo "libre calc nav: Ctrl+Left Arrow   # Moves the cursor to the left edge of the current data range. If the column to the left of the cell that contains the cursor is empty, the cursor moves to the next column to the left that contains data."
echo "libre calc nav: Ctrl+Right Arrow  # Moves the cursor to the right edge of the current data range. If the column to the right of the cell that contains the cursor is empty, the cursor moves to the next column to the right that contains data."
echo "libre calc nav: Ctrl+Up Arrow     # Moves the cursor to the top edge of the current data range. If the row above the cell that contains the cursor is empty, the cursor moves up to the next row that contains data."
echo "libre calc nav: Ctrl+Down Arrow   # Moves the cursor to the bottom edge of the current data range. If the row below the cell that contains the cursor is empty, the cursor moves down to the next row that contains data."
echo "libre calc nav: Ctrl+Shift+Arrow  # Selects all cells containing data from the current cell to the end of the continuous range of data cells, in the direction of the arrow pressed. If used to select rows and columns together, a rectangular cell range is selected."
echo "libre calc nav: Ctrl+Page Up      # Moves one sheet to the left."
echo "libre calc nav: Ctrl+Page Down    # Moves one sheet to the right."
echo "libre calc nav: Alt+Page Up       # Moves one screen to the left."
echo "libre calc nav: Alt+Page Down     # Moves one screen page to the right."
echo "libre calc nav: Shift+Ctrl+Page Up    # Adds the previous sheet to the current selection of sheets. If all the sheets in a spreadsheet are selected, this shortcut key combination only selects the previous sheet. Makes the previous sheet the current sheet."
echo "libre calc nav: Shift+Ctrl+Page Down  # Adds the next sheet to the current selection of sheets. If all the sheets in a spreadsheet are selected, this shortcut key combination only selects the next sheet. Makes the next sheet the current sheet."
echo "libre calc nav: Ctrl+ *           # Selects the data range that contains the cursor. A range is a contiguous cell range that contains data and is bounded by empty row and columns."
echo "libre calc nav: Ctrl+ /           # Selects the matrix formula range that contains the cursor."
echo "libre calc nav: Ctrl+Plus key     # Insert cells (as in menu Insert - Cells)"
echo "libre calc nav: Ctrl+Minus key    # Delete cells (as in menu Edit - Delete Cells)"
echo "libre calc nav: Enter (in a selected range)   # Moves the cursor down one cell in a selected range. To specify the direction that the cursor moves, choose Tools - Options - LibreOffice Calc - General."
echo "libre calc nav: Ctrl+ \`           # Displays or hides the formulas instead of the values in all cells."
echo "---------------------------- LIBREOFFICE CALC FUNCTION KEYS ---------------------------------"
echo "libre calc func: Ctrl+F1          # Displays the comment that is attached to the current cell"
echo "libre calc func: F2               # Switches to Edit mode and places the cursor at the end of the contents of the current cell. Press again to exit Edit mode. If the cursor is in an input box in a dialog that has a Minimize button, the dialog is hidden and the input box remains visible. Press F2 again to show the whole dialog."
echo "libre calc func: Ctrl+F2          # Opens the Function Wizard."
echo "libre calc func: Shift+Ctrl+F2    # Moves the cursor to the Input line where you can enter a formula for the current cell."
echo "libre calc func: Ctrl+F3          # Opens the Define Names dialog."
echo "libre calc func: F4               # Shows or Hides the Database explorer."
echo "libre calc func: Shift+F4         # Rearranges the relative or absolute references (for example, A1, $A$1, $A1, A$1) in the input field."
echo "libre calc func: F5               # Shows or hides the Navigator."
echo "libre calc func: Shift+F5         # Traces dependents."
echo "libre calc func: Shift+F7         # Traces precedents."
echo "libre calc func: Shift+Ctrl+F5    # Moves the cursor from the Input line to the Sheet area box."
echo "libre calc func: F7               # Checks spelling in the current sheet."
echo "libre calc func: Ctrl+F7          # Opens the Thesaurus if the current cell contains text."
echo "libre calc func: F8               # Turns additional selection mode on or off. In this mode, you can use the arrow keys to extend the selection. You can also click in another cell to extend the selection."
echo "libre calc func: Ctrl+F8          # Highlights cells containing values."
echo "libre calc func: F9               # Recalculates changed formulas in the current sheet."
echo "libre calc func: Ctrl+Shift+F9    # Recalculates all formulas in all sheets."
echo "libre calc func: Ctrl+F9          # Updates the selected chart."
echo "libre calc func: F11              # Opens the Styles and Formatting window where you can apply a formatting style to the contents of the cell or to the current sheet."
echo "libre calc func: Shift+F11        # Creates a document template."
echo "libre calc func: Shift+Ctrl+F11   # Updates the templates."
echo "libre calc func: F12              # Groups the selected data range."
echo "libre calc func: Ctrl+F12         # Ungroups the selected data range."
echo "libre calc func: Alt+Down Arrow   # Increases the height of current row (only in OpenOffice.org legacy compatibility mode)."
echo "libre calc func: Alt+Up Arrow     # Decreases the height of current row (only in OpenOffice.org legacy compatibility mode)."
echo "libre calc func: Alt+Right Arrow  # Increases the width of the current column."
echo "libre calc func: Alt+Left Arrow   # Decreases the width of the current column."
echo "libre calc func: Alt+Shift+Arrow  # Optimizes the column width or row height based on the current cell."
echo "----------------------------- LIBREOFFICE CALC FORMAT CELLS  --------------------------------"
echo "libre calc cell format: Ctrl+1          # Open Format Cells dialog"
echo "libre calc cell format: Ctrl+Shift+1    # Two decimal places, thousands separator"
echo "libre calc cell format: Ctrl+Shift+2    # Standard exponential format"
echo "libre calc cell format: Ctrl+Shift+3    # Standard date format"
echo "libre calc cell format: Ctrl+Shift+4    # Standard currency format"
echo "libre calc cell format: Ctrl+Shift+5    # Standard percentage format (two decimal places)"
echo "libre calc cell format: Ctrl+Shift+6    # Standard format"
echo "----------------------------- LIBREOFFICE CALC PIVOT TABLE  ---------------------------------"
echo "libre calc cell pivot: Tab              # Changes the focus by moving forwards through the areas and buttons of the dialog."
echo "libre calc cell pivot: Shift+Tab        # Changes the focus by moving backwards through the areas and buttons of the dialog."
echo "libre calc cell pivot: Up Arrow         # Moves the focus up one item in the current dialog area."
echo "libre calc cell pivot: Down Arrow       # Moves the focus down one item in the current dialog area."
echo "libre calc cell pivot: Left Arrow       # Moves the focus one item to the left in the current dialog area."
echo "libre calc cell pivot: Right Arrow      # Moves the focus one item to the right in the current dialog area."
echo "libre calc cell pivot: Home             # Selects the first item in the current dialog area."
echo "libre calc cell pivot: End              # Selects the last item in the current dialog area."
echo "libre calc cell pivot: Alt              # Copies or moves the current field into the "Row" area."
echo "libre calc cell pivot: Alt              # Copies or moves the current field into the "Column" area."
echo "libre calc cell pivot: Alt              # Copies or moves the current field into the "Data" area."
echo "libre calc cell pivot: Ctrl+Up          # Arrow   Moves the current field up one place."
echo "libre calc cell pivot: Ctrl+Down        # Arrow   Moves the current field down one place."
echo "libre calc cell pivot: Ctrl+Left        # Arrow   Moves the current field one place to the left."
echo "libre calc cell pivot: Ctrl+Right       # Arrow   Moves the current field one place to the right."
echo "libre calc cell pivot: Ctrl+Home        # Moves the current field to the first place."
echo "libre calc cell pivot: Ctrl+End         # Moves the current field to the last place."
echo "libre calc cell pivot: Alt+O            # Displays the options for the current field."
echo "libre calc cell pivot: Delete           # Removes the current field from the area."
echo "################################# CLIPIT #####################################f"
echo "clipit: alt+ctrl+h              # Open clipboard"
echo "clipit: alt+ctrl+f              # Find on history"
echo "################################# SWAY #####################################f"
echo "sway: REMAPS: Esc  CapsLock and CapsLock  Esc"
echo "sway: SUPER + Q                               # Closes window"
echo "sway: SUPER + Enter                           # Opens a new termial"
echo "sway: SUPER + LEFT or SUPER + H               # Focus on left window"
echo "sway: SUPER + RIGHT or SUPER + L              # Focus on right window"
echo "sway: SUPER + UP or SUPER + K                 # Focus on up window"
echo "sway: SUPER + DOWN or SUPER + J               # Focus on down window"
echo "sway: SUPER + SHIFT + LEFT or SUPER + SHIFT + H = Move window to the left"
echo "sway: SUPER + SHIFT + RIGHT or SUPER + SHIFT + L = Move window to the right"
echo "sway: SUPER + SHIFT + UP or SUPER + SHIFT + K = Move window to up"
echo "sway: SUPER + SHIFT + DOWN or SUPER + SHIFT + J = Move window to down"
echo "sway: SUPER + 1                               # Change to workspace 1"
echo "sway: SUPER + 2                               # Change to workspace 2"
echo "sway: SUPER + 3                               # Change to workspace 3"
echo "sway: SUPER + n                               # Change to workspace n"
echo "sway: SUPER + SHIFT + 1                       # Move container to workspace 1"
echo "sway: SUPER + SHIFT + 2                       # Move container to workspace 2"
echo "sway: SUPER + SHIFT + 3                       # Move container to workspace 3"
echo "sway: SUPER + SHIFT + n                       # Move container to workspace n"
echo "sway: SUPER + BRIGHTNESS UP                   # Turn on night mode"
echo "sway: SUPER + BRIGHTNESS DOWN                 # Turn off night mode"
echo "sway: SUPER + PRINT                           # Fullscreen print"
echo "sway: SUPER + BACKSPACE                       # Power Menus" 
echo "sway: SUPER + CTRL + F                        # Zathura launcher"
echo "sway: SUPER + SPACE                           # App launcher (rofi)"
echo "sway: SUPER + MOUSE                           # Resize windows"
echo "sway: SUPER + RIGHT MOUSE                     # Move window"
echo "sway: SUPER + V                               # Split vertical"
echo "sway: SUPER + B                               # Split bottom (horizontally)"
echo "sway: SUPER + G                               # Groupped (tabbed)"
echo "sway: SUPER + S                               # Toggle split type (horizontal or vertical)"
echo "sway: SUPER + SHIFT + F                       # Fullscreen"
echo "sway: SUPER + F                               # Toggle floating"
echo "sway: SUPER + A                               # Focus parent container (focus all windows)"
echo "sway: SUPER + Minus                           # Show scratchpad"
echo "sway: SUPER + SHIFT + Minus                   # Move to scratchpad"
echo "sway: SUPER + R                               # Resize windows (Down, Up, Left, Right for resizing or hjkl)"
echo ""
echo "################################# GIMP #####################################"
echo "################################# INKSCAPE #####################################"
echo "################################# SCRIBUS #####################################"
echo "################################# SYNFIG #####################################"
echo "################################# LIGHTWORKS #####################################"
echo "################################# NATRON #####################################"
echo "################################# BLENDER #####################################"
echo "################################# ALIASES #####################################"
echo "################################# SWAY #####################################"
